### ISSUE TITLE
Prebind authentication + converse.rooms.open => 'TypeError: e.split is not a function'

### ISSUE THREAD

**Issue by Juleffel** [jcbrand/converse.js#507]
Hi,
First, thank you and congratulation for this marvelous piece of software :)

I got a test case with a specific error, when you use pre-bind authentification, and conversejs API, the following errors appear in the log : 
The first time : 
'Error: A "url" property or function must be specified' (converse.min.js:236:766649)
The following times : 
'TypeError: e.split is not a function' (converse.min.js:236:704857)

Here is my code : 

```javascript
require(['converse'], function (converse) {
    converse.listen.on('initialized', function(ev) {
        converse.rooms.open('tmsl@conference.conversejs.org', 'testtest');
    });
    converse.initialize({
        bosh_service_url: 'https://conversejs.org/http-bind/', 
        auto_login: true,
        authentication: 'prebind',
        prebind_url: '/xmpp_prebind_test',
        keepalive: true,
        jid: 'testtest@conversejs.org',
    });
});
```

Displaying the stack at the moment of error, we are in the function 'converse.rooms.open'.

Without prebind, this error doesn't appear. The first time, the room doesn't appear. The following times, the room appear and we change of bug. It may also produce some other underlying errors, as I have a lot of problems with prebind, after calling this piece of code (mostly with the contacts). I will try to have other test cases with the bugs I have with contacts API, but for the moment it's pretty erratic..

I am working with Release 0.9.6, 12 October 2015, on a blank page with only this code running. Same errors appear both on Firefox & Chrome. I have built a running demo on : 
http://timemapstoryline2-juleffel.c9.io/test_converse
Calling the prebind here : 
http://timemapstoryline2-juleffel.c9.io/xmpp_prebind_test

Thank you for your time and help !

**Comment by jcbrand** [comment]
Thanks @Juleffel 

That is a Backbone error and it means that the `sync` method is called to store Backbone models. However, in order to store Backbone models, they need to have a `url` property, or (in the case of converse.js) they need to have the `browserStorage` property (so that models can be stored in `window.sessionStorage`).

In converse.js we only add the `browserStorage` property after the user has logged in, because we need the JID of the current user in order to unique store the data in `sessionStorage`.

Not sure what's happening in your case, but either the user isn't actually logged in when you call `converse.rooms.open`, or for some other reason `sync` is called before the `browserStorage` property was set.

I hope that helps you somewhat with debugging.

**Comment by Juleffel** [comment]
Ok thank you ! It explain why the bug append with prebind and not with auto_login, as the prebind call is longer. I changed the "converse.listen.on('initialized',... " to "converse.listen.on('ready',... " and it works well.

I close, as it is solved.
